services:
  - type: web
    name: portail-scolaire-api
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DB_SERVER
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: ODBC Driver 18 for SQL Server
      - key: DB_ENCRYPT
        value: yes
      - key: DB_TRUST_SERVER_CERT
        value: no

  - type: web
    name: portail-scolaire-web
    env: docker
    plan: free
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: portail-scolaire-api
          property: url
