# Exported from Render on 2026-03-10T01:05:39Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Base_des_donn-es_2
      runtime: docker
      repo: https://github.com/Kefimba/Base_des_donn-es_2
      plan: free
      envVars:
      - key: DB_TRUST_SERVER_CERT
        sync: false
      - key: DB_ENCRYPT
        sync: false
      - key: DB_DRIVER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SERVER
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
